export const MailSettingsOption1 = [
    { name: 'なし', value: 0 },
    { name: '1時間毎', value: 1 },
    { name: '2時間毎', value: 2 },
    { name: '3時間毎', value: 3 },
    { name: '4時間毎', value: 4 },
    { name: '6時間毎', value: 6 },
    { name: '毎日', value: 8 },
    { name: '毎日2回', value: 16 },
];

export const mapScaleRateOptions = [
    { value:"",name: "--"},
    { value: "1", name: "1" },
    { value: "2", name: "2" },
    { value: "3", name: "3" },
    { value: "4", name: "4" },
    { value: "5", name: "5" },
    { value: "6", name: "6" },
    { value: "7", name: "7" },
    { value: "8", name: "8" },
    { value: "9", name: "9" },
    { value: "10", name: "10" },
    { value: "11", name: "11" },
    { value: "12", name: "12" },
    { value: "13", name: "13" },
    { value: "14", name: "14" },
    { value: "15", name: "15" },
    { value: "16", name: "16" },
    { value: "17", name: "17" },
    { value: "18", name: "18" },
    { value: "19", name: "19" },
    { value: "20", name: "20" },
    { value: "21", name: "21" },
    { value: "22", name: "22" },
    { value: "23", name: "23" },
    { value: "24", name: "24" },
    { value: "25", name: "25" },
];

export const urlRegister = [
    'pre-register',
    'pre-register-list',
    'privacy'
]

export const prefectures = [
    { value: "", name: '--' },
    { value: 1, name: '北海道' },
    { value: 2, name: '青森県' },
    { value: 3, name: '岩手県' },
    { value: 4, name: '宮城県' },
    { value: 5, name: '秋田県' },
    { value: 6, name: '山形県' },
    { value: 7, name: '福島県' },
    { value: 8, name: '茨城県' },
    { value: 9, name: '栃木県' },
    { value: 10, name: '群馬県' },
    { value: 11, name: '埼玉県' },
    { value: 12, name: '千葉県' },
    { value: 13, name: '東京都' },
    { value: 14, name: '神奈川県' },
    { value: 15, name: '新潟県' },
    { value: 16, name: '富山県' },
    { value: 17, name: '石川県' },
    { value: 18, name: '福井県' },
    { value: 19, name: '山梨県' },
    { value: 20, name: '長野県' },
    { value: 21, name: '岐阜県' },
    { value: 22, name: '静岡県' },
    { value: 23, name: '愛知県' },
    { value: 24, name: '三重県' },
    { value: 25, name: '滋賀県' },
    { value: 26, name: '京都府' },
    { value: 27, name: '大阪府' },
    { value: 28, name: '兵庫県' },
    { value: 29, name: '奈良県' },
    { value: 30, name: '和歌山県' },
    { value: 31, name: '鳥取県' },
    { value: 32, name: '島根県' },
    { value: 33, name: '岡山県' },
    { value: 34, name: '広島県' },
    { value: 35, name: '山口県' },
    { value: 36, name: '徳島県' },
    { value: 37, name: '香川県' },
    { value: 38, name: '愛媛県' },
    { value: 39, name: '高知県' },
    { value: 40, name: '福岡県' },
    { value: 41, name: '佐賀県' },
    { value: 42, name: '長崎県' },
    { value: 43, name: '熊本県' },
    { value: 44, name: '大分県' },
    { value: 45, name: '宮崎県' },
    { value: 46, name: '鹿児島県' },
    { value: 47, name: '沖縄県' },
];

export const prefectures_en = [
    { value: "", name: '--' },
    { value: 1, name: 'Hokkaido' },
    { value: 2, name: 'Aomori' },
    { value: 3, name: 'Iwate' },
    { value: 4, name: 'Miyagi' },
    { value: 5, name: 'Akita' },
    { value: 6, name: 'Yamagata' },
    { value: 7, name: 'Fukushima' },
    { value: 8, name: 'Ibaraki' },
    { value: 9, name: 'Tochigi' },
    { value: 10, name: 'Gunma' },
    { value: 11, name: 'Saitama' },
    { value: 12, name: 'Chiba' },
    { value: 13, name: 'Tokyo' },
    { value: 14, name: 'Kanagawa' },
    { value: 15, name: 'Niigata' },
    { value: 16, name: 'Toyama' },
    { value: 17, name: 'Ishikawa' },
    { value: 18, name: 'Fukui' },
    { value: 19, name: 'Yamanashi' },
    { value: 20, name: 'Nagano' },
    { value: 21, name: 'Gifu' },
    { value: 22, name: 'Shizuoka' },
    { value: 23, name: 'Aichi' },
    { value: 24, name: 'Mie' },
    { value: 25, name: 'Shiga' },
    { value: 26, name: 'Kyoto' },
    { value: 27, name: 'Osaka' },
    { value: 28, name: 'Hyogo' },
    { value: 29, name: 'Nara' },
    { value: 30, name: 'Wakayama' },
    { value: 31, name: 'Tottori' },
    { value: 32, name: 'Shimane' },
    { value: 33, name: 'Okayama' },
    { value: 34, name: 'Hiroshima' },
    { value: 35, name: 'Yamaguchi' },
    { value: 36, name: 'Tokushima' },
    { value: 37, name: 'Kagawa' },
    { value: 38, name: 'Ehime' },
    { value: 39, name: 'Kochi' },
    { value: 40, name: 'Fukuoka' },
    { value: 41, name: 'Saga' },
    { value: 42, name: 'Nagasaki' },
    { value: 43, name: 'Kumamoto' },
    { value: 44, name: 'Oita' },
    { value: 45, name: 'Miyazaki' },
    { value: 46, name: 'Kagoshima' },
    { value: 47, name: 'Okinawa' },
];

export const staff_dashboard_status_en = ['Maximum Capacity', 'Total Family', 'Blank'];

export const staff_dashboard_status_jp = ['避難可能人数', '現在の避難者数', '追加受入可能人数'];

export const gender_jp = [
    { value: "", name: '--' },
    { value: "1", name: '男' },
    { value: "2", name: '女' },
    { value: "3", name: '答えたくない' },
  ];
  
export const gender_en = [
    { value: "", name: '--' },
    { value: "1", name: 'Male' },
    { value: "2", name: 'Female' },
    { value: "3", name: 'Other' },
];

export const prefecturesCombined = {
    0: { en: '', ja: '' }, 
    1: { en: 'Hokkaido', ja: '北海道' },
    2: { en: 'Aomori', ja: '青森県' },
    3: { en: 'Iwate', ja: '岩手県' },
    4: { en: 'Miyagi', ja: '宮城県' },
    5: { en: 'Akita', ja: '秋田県' },
    6: { en: 'Yamagata', ja: '山形県' },
    7: { en: 'Fukushima', ja: '福島県' },
    8: { en: 'Ibaraki', ja: '茨城県' },
    9: { en: 'Tochigi', ja: '栃木県' },
    10: { en: 'Gunma', ja: '群馬県' },
    11: { en: 'Saitama', ja: '埼玉県' },
    12: { en: 'Chiba', ja: '千葉県' },
    13: { en: 'Tokyo', ja: '東京都' },
    14: { en: 'Kanagawa', ja: '神奈川県' },
    15: { en: 'Niigata', ja: '新潟県' },
    16: { en: 'Toyama', ja: '富山県' },
    17: { en: 'Ishikawa', ja: '石川県' },
    18: { en: 'Fukui', ja: '福井県' },
    19: { en: 'Yamanashi', ja: '山梨県' },
    20: { en: 'Nagano', ja: '長野県' },
    21: { en: 'Gifu', ja: '岐阜県' },
    22: { en: 'Shizuoka', ja: '静岡県' },
    23: { en: 'Aichi', ja: '愛知県' },
    24: { en: 'Mie', ja: '三重県' },
    25: { en: 'Shiga', ja: '滋賀県' },
    26: { en: 'Kyoto', ja: '京都府' },
    27: { en: 'Osaka', ja: '大阪府' },
    28: { en: 'Hyogo', ja: '兵庫県' },
    29: { en: 'Nara', ja: '奈良県' },
    30: { en: 'Wakayama', ja: '和歌山県' },
    31: { en: 'Tottori', ja: '鳥取県' },
    32: { en: 'Shimane', ja: '島根県' },
    33: { en: 'Okayama', ja: '岡山県' },
    34: { en: 'Hiroshima', ja: '広島県' },
    35: { en: 'Yamaguchi', ja: '山口県' },
    36: { en: 'Tokushima', ja: '徳島県' },
    37: { en: 'Kagawa', ja: '香川県' },
    38: { en: 'Ehime', ja: '愛媛県' },
    39: { en: 'Kochi', ja: '高知県' },
    40: { en: 'Fukuoka', ja: '福岡県' },
    41: { en: 'Saga', ja: '佐賀県' },
    42: { en: 'Nagasaki', ja: '長崎県' },
    43: { en: 'Kumamoto', ja: '熊本県' },
    44: { en: 'Oita', ja: '大分県' },
    45: { en: 'Miyazaki', ja: '宮崎県' },
    46: { en: 'Kagoshima', ja: '鹿児島県' },
    47: { en: 'Okinawa', ja: '沖縄県' },
};

export const default_place_id = [1,2,3,4];